##https://docker-docs.netlify.app/get-started/part3/#your-first-docker-composeyml-file
#https://medium.com/@vinodkrane/microservices-scaling-and-load-balancing-using-docker-compose-78bf8dc04da9
version: "3"
services:
  redis:
    image: redis
    networks:
      - djangonetwork
  database:
    image: postgis/postgis
    environment:
     - POSTGRES_PASSWORD=gispassword
    volumes:
     - /home/radhakrishna/projects/database/geospatialdata:/var/lib/postgresql/data
    networks:
      - djangonetwork
  data_poller:
    build: backend/
    command: 'sh /code/defaults.sh'
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    networks:
      - djangonetwork
  backend:
    build: backend/
    command: 'sh /code/server.sh'
    links:
     - database
     - redis
    depends_on:
     - database
     - redis
     
    expose:
      - "8000"
    networks:
      - djangonetwork
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    links:
      - backend
    ports:
      - "4000:4000"
    networks:
      - djangonetwork
networks:
  djangonetwork:
      driver: bridge





  